version: 2.1
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install git & vim
          command: apk --no-cache add git neovim

      - run:
          name: Setup VIM
          command: mkdir -p ~/.config/nvim/pack/plugins/start/

      - checkout:
          path: "~/.config/nvim/pack/plugins/start/vim-testify"

      - run:
          name: Run tests
          command: cd ~/.config/nvim/pack/plugins/start/vim-testify; nvim +"set hidden" +TestifySuite +qa

      - run:
          name: View Test Results
          command: cat ~/.config/nvim/pack/plugins/start/vim-testify/testify_results.txt
