version: 2.1
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install git & vim
          command: apk --no-cache add git vim

      - run:
          name: Setup VIM
          command: mkdir -p ~/.vim/pack/plugins/start/

      - checkout:
          path: '~/.vim/pack/plugins/start/vim-testify'

      - run:
          name: Run tests
          command: cd ~/.vim/pack/plugins/start/vim-testify; vim +"set hidden" +TestifySuite

