name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tests:
    name: Testify Tests
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: pack/plugins/start/vim-testify

      - name: Install Vim or neovim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
          version: nightly

      - name: Run unit tests on nvim
        if: ${{ matrix.neovim }}
        env:
          VIM: ${{ steps.vim.outputs.executable }}
        run: |
          cd ${{ github.workspace }}/pack/plugins/start/vim-testify
          echo "set packpath+=${{ github.workspace }}" > vimrc
          ${VIM} --headless -u vimrc +TestifySuite +qall

      - name: Run unit tests on vim
        if: ${{ !matrix.neovim }}
        env:
          VIM: ${{ steps.vim.outputs.executable }}
        run: |
          cd ${{ github.workspace }}/pack/plugins/start/vim-testify
          echo "set packpath+=${{ github.workspace }}" > vimrc
          ${VIM} -u vimrc +TestifySuite +qall
          cat testify_results.txt
